-- MySQL Script generated by MySQL Workbench
-- Sun May  5 00:48:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hotel` ;

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`roomtypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`roomtypes` ;

CREATE TABLE IF NOT EXISTS `hotel`.`roomtypes` (
  `RoomTypeID` INT(6) NOT NULL AUTO_INCREMENT,
  `RoomTypeName` VARCHAR(45) NOT NULL,
  `RoomTypeDescription` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`RoomTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`rooms` ;

CREATE TABLE IF NOT EXISTS `hotel`.`rooms` (
  `RoomID` INT(9) NOT NULL AUTO_INCREMENT,
  `RoomNumber` INT(6) NOT NULL,
  `RoomFloor` INT(4) NOT NULL,
  `RoomOccupancy` INT(3) NOT NULL,
  `RoomTypeID` INT(6) NOT NULL,
  PRIMARY KEY (`RoomID`),
  CONSTRAINT `fk_Rooms_RoomTypeID`
    FOREIGN KEY (`RoomTypeID`)
    REFERENCES `hotel`.`roomtypes` (`RoomTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `rooms_RoomNumber_Unique` ON `hotel`.`rooms` (`RoomNumber` ASC);

CREATE INDEX `fk_Rooms_RoomTypeID_Idx` ON `hotel`.`rooms` (`RoomTypeID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`amenities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`amenities` ;

CREATE TABLE IF NOT EXISTS `hotel`.`amenities` (
  `RoomAmenityID` INT(6) NOT NULL AUTO_INCREMENT,
  `RoomAmenityName` VARCHAR(45) NOT NULL,
  `RoomAmenityDescription` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`RoomAmenityID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`postalcode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`postalcode` ;

CREATE TABLE IF NOT EXISTS `hotel`.`postalcode` (
  `ZipCode` CHAR(5) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ZipCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`customeraddresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`customeraddresses` ;

CREATE TABLE IF NOT EXISTS `hotel`.`customeraddresses` (
  `AddressID` INT(12) NOT NULL,
  `StreetAddress` VARCHAR(256) NOT NULL,
  `ZipCode` CHAR(5) NOT NULL,
  PRIMARY KEY (`AddressID`),
  CONSTRAINT `fk_CustomerAddresses_ZipCode`
    FOREIGN KEY (`ZipCode`)
    REFERENCES `hotel`.`postalcode` (`ZipCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CustomerAddresses_ZipCode_Idx` ON `hotel`.`customeraddresses` (`ZipCode` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`customers` ;

CREATE TABLE IF NOT EXISTS `hotel`.`customers` (
  `CustomerID` INT(12) NOT NULL,
  `CustomerFirstName` VARCHAR(45) NOT NULL,
  `CustomerLastName` VARCHAR(45) NOT NULL,
  `CustomerEmail` VARCHAR(256) NULL,
  `AddressID` INT(12) NOT NULL,
  PRIMARY KEY (`CustomerID`),
  CONSTRAINT `fk_customers_addressID`
    FOREIGN KEY (`AddressID`)
    REFERENCES `hotel`.`customeraddresses` (`AddressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Customers_AddressID_Idx` ON `hotel`.`customers` (`AddressID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`guests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`guests` ;

CREATE TABLE IF NOT EXISTS `hotel`.`guests` (
  `GuestID` INT(12) NOT NULL,
  `CustomerID` INT(9) NOT NULL,
  `GuestName` VARCHAR(45) NOT NULL,
  `GuestAge` INT(3) NOT NULL,
  PRIMARY KEY (`GuestID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`reservations` ;

CREATE TABLE IF NOT EXISTS `hotel`.`reservations` (
  `ReservationID` INT(12) NOT NULL AUTO_INCREMENT,
  `ReservationCheckInDate` DATE NOT NULL,
  `ReservationCheckOutDate` DATE NOT NULL,
  `CustomerID` INT(12) NOT NULL,
  PRIMARY KEY (`ReservationID`),
  CONSTRAINT `fk_Customers_CustomerID`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `hotel`.`customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Customers_CustomerID_Idx` ON `hotel`.`reservations` (`CustomerID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`rates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`rates` ;

CREATE TABLE IF NOT EXISTS `hotel`.`rates` (
  `RoomRateID` INT(12) NOT NULL,
  `RoomRateName` VARCHAR(64) NOT NULL,
  `RoomRatePrice` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`RoomRateID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`reservationsroomsguestsbridge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`reservationsroomsguestsbridge` ;

CREATE TABLE IF NOT EXISTS `hotel`.`reservationsroomsguestsbridge` (
  `ReservationID` INT(12) NOT NULL,
  `RoomID` INT(9) NOT NULL,
  `GuestID` INT(12) NOT NULL,
  PRIMARY KEY (`ReservationID`, `RoomID`, `GuestID`),
  CONSTRAINT `fk_Reservations.ReservationID`
    FOREIGN KEY (`ReservationID`)
    REFERENCES `hotel`.`reservations` (`ReservationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rooms.RoomID`
    FOREIGN KEY (`RoomID`)
    REFERENCES `hotel`.`rooms` (`RoomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Guests.GuestID`
    FOREIGN KEY (`GuestID`)
    REFERENCES `hotel`.`guests` (`GuestID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Rooms_RoomID_Idx` ON `hotel`.`reservationsroomsguestsbridge` (`RoomID` ASC);

CREATE INDEX `fk_Guests_GuestID_Idx` ON `hotel`.`reservationsroomsguestsbridge` (`GuestID` ASC);

CREATE INDEX `fk_Reservations_ReservationID_Idx` ON `hotel`.`reservationsroomsguestsbridge` (`ReservationID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`addons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`addons` ;

CREATE TABLE IF NOT EXISTS `hotel`.`addons` (
  `AddOnID` INT(12) NOT NULL,
  `AddOnName` VARCHAR(45) NOT NULL,
  `AddOnPrice` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`AddOnID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`addonsreservationsbridge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`addonsreservationsbridge` ;

CREATE TABLE IF NOT EXISTS `hotel`.`addonsreservationsbridge` (
  `AddOnID` INT(12) NOT NULL,
  `ReservationID` INT(12) NOT NULL,
  `BeginDate` DATE NOT NULL,
  `EndDate` DATE NOT NULL,
  PRIMARY KEY (`AddOnID`, `ReservationID`, `BeginDate`, `EndDate`),
  CONSTRAINT `fk_addons_reservations_addons`
    FOREIGN KEY (`AddOnID`)
    REFERENCES `hotel`.`addons` (`AddOnID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_addons_reservations_reservations1`
    FOREIGN KEY (`ReservationID`)
    REFERENCES `hotel`.`reservations` (`ReservationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_addons_reservations_reservations_Idx` ON `hotel`.`addonsreservationsbridge` (`ReservationID` ASC);

CREATE INDEX `fk_addons_reservations_addons_Idx` ON `hotel`.`addonsreservationsbridge` (`AddOnID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`promotioncodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`promotioncodes` ;

CREATE TABLE IF NOT EXISTS `hotel`.`promotioncodes` (
  `PromotionCodesID` INT(12) NOT NULL,
  `PromotionName` VARCHAR(45) NOT NULL,
  `PromotionPercent` DECIMAL(3,2) NULL,
  `PromotionAmountDiscount` DECIMAL(5,2) NULL,
  PRIMARY KEY (`PromotionCodesID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`promotioncodesreservationsbridge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`promotioncodesreservationsbridge` ;

CREATE TABLE IF NOT EXISTS `hotel`.`promotioncodesreservationsbridge` (
  `PromotionCodesID` INT(12) NOT NULL,
  `ReservationID` INT(12) NOT NULL,
  `BeginDate` DATE NOT NULL,
  `EndDate` DATE NOT NULL,
  PRIMARY KEY (`PromotionCodesID`, `ReservationID`, `BeginDate`, `EndDate`),
  CONSTRAINT `fk_PromotionCodes_PromotionCodesID`
    FOREIGN KEY (`PromotionCodesID`)
    REFERENCES `hotel`.`promotioncodes` (`PromotionCodesID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservations_ReservationID`
    FOREIGN KEY (`ReservationID`)
    REFERENCES `hotel`.`reservations` (`ReservationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Reservations_ReservationID_Idx` ON `hotel`.`promotioncodesreservationsbridge` (`ReservationID` ASC);

CREATE INDEX `fk_PromotionCodes_PromotionCodesID_Idx` ON `hotel`.`promotioncodesreservationsbridge` (`PromotionCodesID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`billdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`billdetails` ;

CREATE TABLE IF NOT EXISTS `hotel`.`billdetails` (
  `BillDetailID` INT(12) NOT NULL,
  `RoomCharges` DECIMAL(8,2) NULL,
  `MealCharges` DECIMAL(6,2) NULL,
  `MovieCharges` DECIMAL(6,2) NULL,
  `OtherAddOns` DECIMAL(6,2) NULL,
  `ReservationID` INT(12) NULL,
  PRIMARY KEY (`BillDetailID`),
  CONSTRAINT `fk_Reservations_ReservationID_BillDetails`
    FOREIGN KEY (`ReservationID`)
    REFERENCES `hotel`.`reservations` (`ReservationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Reservations_ReservationID_BillDetails_Idx` ON `hotel`.`billdetails` (`ReservationID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`billtotalsheader`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`billtotalsheader` ;

CREATE TABLE IF NOT EXISTS `hotel`.`billtotalsheader` (
  `BillTotalsID` INT(12) NOT NULL,
  `RoomTotal` DECIMAL(8,2) NULL,
  `AddOnTotal` DECIMAL(8,2) NULL,
  `TaxesTotal` DECIMAL(8,2) NULL,
  `GrandTotal` DECIMAL(8,2) NULL,
  `BillDetailsID` INT(12) NULL,
  PRIMARY KEY (`BillTotalsID`),
  CONSTRAINT `fk_BillDetails_BillDetailID`
    FOREIGN KEY (`BillDetailsID`)
    REFERENCES `hotel`.`billdetails` (`BillDetailID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_BillDetals_BillDetailsID_Idx` ON `hotel`.`billtotalsheader` (`BillDetailsID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`roomsamenitiesbridge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`roomsamenitiesbridge` ;

CREATE TABLE IF NOT EXISTS `hotel`.`roomsamenitiesbridge` (
  `RoomID` INT(9) NOT NULL,
  `RoomAmenityID` INT(6) NOT NULL,
  PRIMARY KEY (`RoomID`, `RoomAmenityID`),
  CONSTRAINT `fk_Rooms_RoomID`
    FOREIGN KEY (`RoomID`)
    REFERENCES `hotel`.`rooms` (`RoomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Amenities_RoomAmenityid`
    FOREIGN KEY (`RoomAmenityID`)
    REFERENCES `hotel`.`amenities` (`RoomAmenityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Amenities_AmenitiesID_Idx` ON `hotel`.`roomsamenitiesbridge` (`RoomAmenityID` ASC);

CREATE INDEX `fk_Rooms_RoomID_Idx` ON `hotel`.`roomsamenitiesbridge` (`RoomID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`roomtypesratesbridge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`roomtypesratesbridge` ;

CREATE TABLE IF NOT EXISTS `hotel`.`roomtypesratesbridge` (
  `RoomTypeID` INT(6) NOT NULL,
  `RoomRateID` INT(12) NOT NULL,
  `BeginDate` DATE NOT NULL,
  `Enddate` DATE NOT NULL,
  PRIMARY KEY (`RoomTypeID`, `RoomRateID`, `BeginDate`, `Enddate`),
  CONSTRAINT `fk_Roomtypes_RoomTypeID`
    FOREIGN KEY (`RoomTypeID`)
    REFERENCES `hotel`.`roomtypes` (`RoomTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rates_RoomRatesID`
    FOREIGN KEY (`RoomRateID`)
    REFERENCES `hotel`.`rates` (`RoomRateID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Rates_RoomRateID_Idx` ON `hotel`.`roomtypesratesbridge` (`RoomRateID` ASC);

CREATE INDEX `fk_RoomTypes_RoomTypeID_Idx` ON `hotel`.`roomtypesratesbridge` (`RoomTypeID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`ROOM_TYPES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`ROOM_TYPES` ;

CREATE TABLE IF NOT EXISTS `hotel`.`ROOM_TYPES` (
  `RoomTypeID` INT NOT NULL,
  `RoomTypeDescription` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RoomTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`ROOMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`ROOMS` ;

CREATE TABLE IF NOT EXISTS `hotel`.`ROOMS` (
  `RoomTypeID` INT NOT NULL,
  `RoomNum` INT GENERATED ALWAYS AS () VIRTUAL,
  `Floor` VARCHAR(3) NOT NULL,
  `OccupancyLimit` INT NULL,
  PRIMARY KEY (`RoomNum`),
  CONSTRAINT `FK_RoomTypeID`
    FOREIGN KEY (`RoomTypeID`)
    REFERENCES `hotel`.`ROOM_TYPES` (`RoomTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`AMENITIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`AMENITIES` ;

CREATE TABLE IF NOT EXISTS `hotel`.`AMENITIES` (
  `AmenityID` INT NOT NULL,
  `Amenity Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AmenityID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`ROOM_AMENITIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`ROOM_AMENITIES` ;

CREATE TABLE IF NOT EXISTS `hotel`.`ROOM_AMENITIES` (
  `ID` INT NOT NULL,
  `RoomID` VARCHAR(45) NOT NULL,
  `AmenityID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_RoomID`
    FOREIGN KEY (`RoomID`)
    REFERENCES `hotel`.`ROOMS` (`RoomNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AmenityID`
    FOREIGN KEY (`AmenityID`)
    REFERENCES `hotel`.`AMENITIES` (`AmenityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_RoomID_idx` ON `hotel`.`ROOM_AMENITIES` (`RoomID` ASC);

CREATE INDEX `FK_AmenityID_idx` ON `hotel`.`ROOM_AMENITIES` (`AmenityID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`ROOM_RATES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`ROOM_RATES` ;

CREATE TABLE IF NOT EXISTS `hotel`.`ROOM_RATES` (
  `ID` INT NOT NULL,
  `RoomTypeID` INT NOT NULL,
  `StartDate` DATE NULL,
  `EndDate` DATE NULL,
  `RoomRate` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `RoomTypeID`
    FOREIGN KEY (`RoomTypeID`)
    REFERENCES `hotel`.`ROOM_TYPES` (`RoomTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `RoomTypeID_UNIQUE` ON `hotel`.`ROOM_RATES` (`RoomTypeID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`CUSTOMERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`CUSTOMERS` ;

CREATE TABLE IF NOT EXISTS `hotel`.`CUSTOMERS` (
  `CustomerID` INT NOT NULL,
  `CustomerName` VARCHAR(45) NOT NULL,
  `CustomerPhone` VARCHAR(45) NOT NULL,
  `CusomertEmail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`GUESTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`GUESTS` ;

CREATE TABLE IF NOT EXISTS `hotel`.`GUESTS` (
  `GuestID` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  `GuestName` VARCHAR(45) NOT NULL,
  `GuestAge` INT NULL,
  PRIMARY KEY (`GuestID`),
  CONSTRAINT `FK_CustomerID`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `hotel`.`CUSTOMERS` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_CustomerID_idx` ON `hotel`.`GUESTS` (`CustomerID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`RESERVATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`RESERVATIONS` ;

CREATE TABLE IF NOT EXISTS `hotel`.`RESERVATIONS` (
  `ReservationID` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NOT NULL,
  PRIMARY KEY (`ReservationID`),
  CONSTRAINT `FK_CustomerID`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `hotel`.`CUSTOMERS` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `CustomerID_UNIQUE` ON `hotel`.`RESERVATIONS` (`CustomerID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`GUEST_ROOM_RESERVATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`GUEST_ROOM_RESERVATIONS` ;

CREATE TABLE IF NOT EXISTS `hotel`.`GUEST_ROOM_RESERVATIONS` (
  `ID` INT NOT NULL,
  `ReservationID` INT NULL,
  `RoomID` INT NULL,
  `GuestID` INT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_ReservationID`
    FOREIGN KEY (`ReservationID`)
    REFERENCES `hotel`.`RESERVATIONS` (`ReservationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RoomID`
    FOREIGN KEY (`RoomID`)
    REFERENCES `hotel`.`ROOMS` (`RoomNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_GuestID`
    FOREIGN KEY (`GuestID`)
    REFERENCES `hotel`.`GUESTS` (`GuestID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_ReservationID_idx` ON `hotel`.`GUEST_ROOM_RESERVATIONS` (`ReservationID` ASC);

CREATE INDEX `FK_RoomID_idx` ON `hotel`.`GUEST_ROOM_RESERVATIONS` (`RoomID` ASC);

CREATE INDEX `FK_GuestID_idx` ON `hotel`.`GUEST_ROOM_RESERVATIONS` (`GuestID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`ADDONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`ADDONS` ;

CREATE TABLE IF NOT EXISTS `hotel`.`ADDONS` (
  `AddOnID` INT NOT NULL,
  `AddOnDescription` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AddOnID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `AddOnDescription_UNIQUE` ON `hotel`.`ADDONS` (`AddOnDescription` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`ADDON_RATES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`ADDON_RATES` ;

CREATE TABLE IF NOT EXISTS `hotel`.`ADDON_RATES` (
  `ID` INT NOT NULL,
  `AddOnID` INT NOT NULL,
  `StartDate` DATE NULL,
  `EndDate` DATE NULL,
  `AddOnRate` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_AddOnID`
    FOREIGN KEY (`AddOnID`)
    REFERENCES `hotel`.`ADDONS` (`AddOnID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_AddOnID_idx` ON `hotel`.`ADDON_RATES` (`AddOnID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`ADDON_USAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`ADDON_USAGE` ;

CREATE TABLE IF NOT EXISTS `hotel`.`ADDON_USAGE` (
  `ID` INT NOT NULL,
  `ReservationID` INT NOT NULL,
  `AddOnID` INT NOT NULL,
  `OrderDate` DATE NOT NULL,
  `Notes` VARCHAR(100) GENERATED ALWAYS AS () VIRTUAL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_ReservationID`
    FOREIGN KEY (`ReservationID`)
    REFERENCES `hotel`.`RESERVATIONS` (`ReservationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AddOnID`
    FOREIGN KEY (`AddOnID`)
    REFERENCES `hotel`.`ADDONS` (`AddOnID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_ReservationID_idx` ON `hotel`.`ADDON_USAGE` (`ReservationID` ASC);

CREATE INDEX `FK_AddOnID_idx` ON `hotel`.`ADDON_USAGE` (`AddOnID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`PROMOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`PROMOS` ;

CREATE TABLE IF NOT EXISTS `hotel`.`PROMOS` (
  `ID` INT NOT NULL,
  `PromoCode` VARCHAR(45) NOT NULL,
  `StartDate` DATE NOT NULL,
  `PROMOScol` VARCHAR(45) NULL,
  `EndDate` DATE NULL,
  `PercentOffDiscount` DECIMAL(10,2) NULL,
  `DollarOffDiscount` DECIMAL(10,2) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`PROMO_USAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`PROMO_USAGE` ;

CREATE TABLE IF NOT EXISTS `hotel`.`PROMO_USAGE` (
  `ID` INT NOT NULL,
  `ReservationID` INT NOT NULL,
  `PromoID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_ReservationID`
    FOREIGN KEY (`ReservationID`)
    REFERENCES `hotel`.`RESERVATIONS` (`ReservationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PromoID`
    FOREIGN KEY (`PromoID`)
    REFERENCES `hotel`.`PROMOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_ReservationID_idx` ON `hotel`.`PROMO_USAGE` (`ReservationID` ASC);

CREATE INDEX `FK_PromoID_idx` ON `hotel`.`PROMO_USAGE` (`PromoID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`BILL_SUMMARY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`BILL_SUMMARY` ;

CREATE TABLE IF NOT EXISTS `hotel`.`BILL_SUMMARY` (
  `BillID` INT NOT NULL,
  `TotalCost` DECIMAL(10,2) NULL,
  `TotalTax` DECIMAL(10,2) NULL,
  `BillDate` DATE NULL,
  `ReservationID` INT NULL,
  PRIMARY KEY (`BillID`),
  CONSTRAINT `FK_ReservationID`
    FOREIGN KEY (`ReservationID`)
    REFERENCES `hotel`.`RESERVATIONS` (`ReservationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_ReservationID_idx` ON `hotel`.`BILL_SUMMARY` (`ReservationID` ASC);


-- -----------------------------------------------------
-- Table `hotel`.`TAX_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`TAX_TYPE` ;

CREATE TABLE IF NOT EXISTS `hotel`.`TAX_TYPE` (
  `ID` INT NOT NULL,
  `TaxTypeDescription` VARCHAR(100) NOT NULL,
  `TaxPercentage` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`BILL_DETAILS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`BILL_DETAILS` ;

CREATE TABLE IF NOT EXISTS `hotel`.`BILL_DETAILS` (
  `ID` INT NOT NULL,
  `BillSummaryID` INT NOT NULL,
  `RoomNum` INT NULL,
  `AmenityID` INT NULL,
  `UsageDate` DATE NULL,
  `UsageCost` DECIMAL(10,2) NULL,
  `TaxTypeID` INT NULL,
  `UsageTax` DECIMAL(10,2) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_RoomNum`
    FOREIGN KEY (`RoomNum`)
    REFERENCES `hotel`.`ROOMS` (`RoomNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AmenityID`
    FOREIGN KEY (`AmenityID`)
    REFERENCES `hotel`.`AMENITIES` (`AmenityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TaxTypeID`
    FOREIGN KEY (`TaxTypeID`)
    REFERENCES `hotel`.`TAX_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BillSummaryID`
    FOREIGN KEY (`BillSummaryID`)
    REFERENCES `hotel`.`BILL_SUMMARY` (`BillID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_RoomNum_idx` ON `hotel`.`BILL_DETAILS` (`RoomNum` ASC);

CREATE INDEX `FK_AmenityID_idx` ON `hotel`.`BILL_DETAILS` (`AmenityID` ASC);

CREATE INDEX `FK_TaxTypeID_idx` ON `hotel`.`BILL_DETAILS` (`TaxTypeID` ASC);

CREATE INDEX `FK_BillSummaryID_idx` ON `hotel`.`BILL_DETAILS` (`BillSummaryID` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
